PRIMAZA_CONFIG: str = "primaza_main_config"
WORKER_CONFIG: str = "primaza_worker_config"
APP_AGENT_CONFIG: str = "application_agent_config"
SVC_AGENT_CONFIG: str = "service_agent_config"
REPOSITORY: str = "primaza/primazactl"
